[package]
name = "query_builder"
version = "0.1.0"
edition = "2018"

[workspace]

[dependencies.query_builder_engine]
path = "query_builder_engine"

[dependencies.query_builder_macros]
path = "query_builder_macros"
